### ISSUE TITLE
feature_decoding_layer_depthwise 

### ISSUE THREAD

**Issue by l53ma** [DylanWusee/pointconv#4]
Hi @DylanWusee,

Thank you for your interesting work! 

Would you mind if you can explain the difference between "feature_decoding_layer_depthwise" and "feature_decoding_layer" functions? I didn't get the hints from your published paper. Also, do you have any ideas about further improvement, especially for large-scale LiDAR datasets, i.e., KITTI.

Cheers,
Lingfei

**Comment by DylanWusee** [comment]
Thank you for your interesting in our work.

Since our work PointConv is a convolution layer on point clouds,  it is easy to derive a depthwise convolution.  "feature_decoding_layer_depthwise" is a depthwise version of convolution. 

About KITTI dataset, I think the main improvement might be on the density side since LiDAR gives very non-uniformly sampled point clouds. 

Thank you for your interest.
Wenxuan

**Comment by l53ma** [comment]
Much clear to me, appreciated it!
