### ISSUE TITLE
Kernel density calculation

### ISSUE THREAD

**Issue by l53ma** [DylanWusee/pointconv#5]
Hi @DylanWusee,

I am a little confused when you calculate the kernel density, why did you choose "N_points = 128" (in the line of 37 in the pointconv_util.py file), how do you determine this value? Or what is the point density/spacing of your ScanNet dataset?

Thanks for your kind assistance again. 

Cheers,
Mark

**Comment by DylanWusee** [comment]
The "N_points" is the neighbor size that is used to compute the density. This should be a scalar between 1 - the size of the point cloud. This "N_points = 128" is just chosen empirically, which need to be adjusted according to the dataset you use. Theoretically, more points should be better. However, there would be a memory issue since we use GPU to compute the density.
